server:
  port: 8999
  displayName: diamond
  context-path: /diamond



jetty:
  threadPool:
      maxThreads: 200
      minThreads: 10
      idleTimeout: 30000

https:
  port: 8777
  keystore-password: 9jx888d35h16rs0
  keystore: /home/ljl/code/tjyddx.cn.jks
  #keystore: provider/src/main/resources/tjyddx.cn.jks
  keystore-type: JKS

spring:
    datasource:
        name: ap
#        url: jdbc:mysql://maisuosi.mysql.rds.aliyuncs.com:3306/diamond?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://tjyddx.cn:3306/questionair?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: test
        password: Ljl123456***
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 16
        initialSize: 4
        maxWait: 3000
        minIdle: 4
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        dbc_connectionInitSqls: SET NAMES utf8mb4
mybatis:
    configLocation: classpath:/mybatis-config.xml


message:
    pusher:
        regionId: cn-beijing
        accessKeyId: LTAIoAqtH1AAgl30
        accessKeySecret: hx1kgkQtASGW1EfoSb6D0QLdvYxm3A
        studentAppKey: 24736957
        teacherAppKey: 24750332

spring.http.converters.preferred-json-mapper: fastjson



