server:
  port: 8999
  displayName: diamond
  context-path: /ap



jetty:
  threadPool:
      maxThreads: 200
      minThreads: 10
      idleTimeout: 30000

spring:
    datasource:
        name: ap
#        url: jdbc:mysql://maisuosi.mysql.rds.aliyuncs.com:3306/diamond?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#        username: adminuser
#        password: Catfish123
        url: jdbc:mysql://localhost:3306/questionair?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 16
        initialSize: 4
        maxWait: 3000
        minIdle: 4
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        dbc_connectionInitSqls: SET NAMES utf8mb4
mybatis:
    configLocation: classpath:/mybatis-config.xml


message:
    pusher:
        regionId: cn-beijing
        accessKeyId: LTAIoAqtH1AAgl30
        accessKeySecret: hx1kgkQtASGW1EfoSb6D0QLdvYxm3A
        studentAppKey: 24736957
        teacherAppKey: 24750332

#kafka:
#    server: 127.0.0.1:9092
#    acks: all
#    retries: 2
#    batch-size: 16384
#    linger-ms: 2
#    buffer-memory: 33554432

#    kafka:
#        consumer:
#          enable-auto-commit: true
#          group-id: applog
#          auto-offset-reset: latest
#          bootstrap-servers: 172.19.159.233:9092

spring.http.converters.preferred-json-mapper: fastjson


